force-app/main/default/objects/Nylas_V3_Setting__mdt/Nylas_V3_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for the Nylas API V3 Apex SDK.</description>
    <label>Nylas V3 Setting</label>
    <pluralLabel>Nylas V3 Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Nylas_V3_Setting__mdt/fields/Callback_URI__c.field-meta.xml
<CustomField>
    <fullName>Callback_URI__c</fullName>
    <description>Nylas hosted auth callback URI which handles the verification of newly created grants.</description>
    <label>Callback URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nylas_V3_Setting__mdt/fields/Nylas_API_Secret__c.field-meta.xml
<CustomField>
    <fullName>Nylas_API_Secret__c</fullName>
    <label>Nylas API Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nylas_V3_Setting__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region which API requests will be routed to.</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/config/NylasConfig.cls
/**
 * @description       : Singleton class for managing Nylas V3 SDK custom metadata configuration
 * @author            : Lincoln Rychecky
 * @group             :
 * @last modified on  : 07-03-2024
 * @last modified by  : Lincoln Rychecky
 **/

public with sharing class NylasConfig {
  private static NylasConfig instance = null;
  public Nylas_V3_Setting__mdt nylasSettings;
  private final String SETTING_NAME = 'System_Config'; // the default nylas setting custom metadata instance that is installed with the package

  private NylasConfig() {
    // if testing, we need to set the nylasSettings manually to placeholder values
    if (Test.isRunningTest()) {
      nylasSettings = new Nylas_V3_Setting__mdt(
        DeveloperName = 'System_Config',
        Callback_URI__c = 'placeholder',
        Client_ID__c = 'placeholder',
        Nylas_API_Secret__c = 'placeholder',
        Region__c = 'US'
      );
    } else {
      Nylas_V3_Setting__mdt nylasSettings = Nylas_V3_Setting__mdt.getInstance(
        SETTING_NAME
      );

      if (nylasSettings != null) {
        this.nylasSettings = nylasSettings;
      }
    }
  }

  public static NylasConfig getNylasConfig() {
    if (instance == null) {
      instance = new NylasConfig();
    }
    return instance;
  }
}