force-app/main/default/objects/Nylas_V3_Setting__mdt/Nylas_V3_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for the Nylas API V3 Apex SDK.</description>
    <label>Nylas V3 Setting</label>
    <pluralLabel>Nylas V3 Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Nylas_V3_Setting__mdt/fields/Nylas_API_Secret__c.field-meta.xml
<CustomField>
    <fullName>Nylas_API_Secret__c</fullName>
    <label>Nylas API Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nylas_V3_Setting__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region which API requests will be routed to.</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NylasHTTPUtility.cls
public class NylasHTTPUtility {
  private static Nylas_V3_Setting__mdt nylasSettings = NylasConfig.getNylasConfig()
    .nylasSettings;

  // the base url for the Nylas API ('https://api.us.nylas.com' or 'https://api.eu.nylas.com')
  private static String baseURL = nylasSettings.Region__c == 'US' ||
  nylasSettings.Region__c == null
  ? 'https://api.us.nylas.com'
  : 'https://api.eu.nylas.com';

  private static String nylasAPISecret = nylasSettings.Nylas_API_Secret__c;

  // Enum for HTTP methods
  public enum HttpMethod {
    GET,
    POST,
    PUT,
    DEL,
    PATCH,
    HEAD,
    OPTIONS
  }

  public static HttpRequest newRequest(HttpMethod method, String url) {
    // Define the endpoint URL
    String endpointUrl = baseURL + url;
    String versionNumber = PackageVersion.VERSION_NUMBER;

    // Make post request to the endpoint
    HttpRequest req = new HttpRequest();
    req.setEndpoint(endpointUrl);
    req.setMethod(method == HttpMethod.DEL ? 'DELETE' : method.name());
    req.setHeader('Content-Type', 'application/json');
    req.setHeader('Authorization', 'Bearer ' + nylasAPISecret);
    req.setHeader('User-Agent', 'Nylas-SFDC-SDK v' + versionNumber);

    return req;
  }

  public static HttpRequest newRequest(
    HttpMethod method,
    String url,
    String customAuthToken
  ) {
    // Define the endpoint URL
    String endpointUrl = baseURL + url;

    // Make post request to the endpoint
    HttpRequest req = new HttpRequest();
    req.setEndpoint(endpointUrl);
    req.setMethod(method == HttpMethod.DEL ? 'DELETE' : method.name());
    req.setHeader('Content-Type', 'application/json');
    req.setHeader('Authorization', 'Bearer ' + customAuthToken);
    req.setHeader('User-Agent', 'Nylas-SFDC-SDK-version');

    return req;
  }
}